# These are supported funding model platforms

# GitHub Sponsors
github: # [yourusername]

# Open Collective
open_collective: # your-project

# Ko-fi
ko_fi: # yourusername

# Tidelift
tidelift: # npm/package-name

# Community Bridge
community_bridge: # project-name

# Liberapay
liberapay: # username

# IssueHunt
issuehunt: # username

# Otechie
otechie: # username

# LFX Crowdfunding (Linux Foundation)
lfx_crowdfunding: # project-name

# Custom
custom: # ['https://www.paypal.me/username', 'https://buy.me.a.coffee/username']

