import { Terminal, Layers, LineChart, Wallet, Activity, Database, Search, Bell, Coins, BarChart, Code, Plus } from "lucide-react"

export const toolsContent = {
  title: "Useful Tools for Baking",
  description: "Essential tools and resources to help you manage your baking operations effectively.",
  cards: [
    {
      icon: Layers,
      title: "TezBake (BakeBuddy)",
      description: "Easy to use Tezos baking software for both beginners and experts.",
      linkText: "View tool",
      href: "https://www.bakebuddy.xyz/",
    },
    {
      icon: Terminal,
      title: "Kiln",
      description: "GUI tool for baking on Tezos. Easy to set up and monitor your baker.",
      linkText: "View tool",
      href: "https://tezos-kiln.net/",
    },
    {
      icon: Wallet,
      title: "TezPay",
      description: "Automated payout tool for Tezos bakers to distribute rewards to delegators.",
      linkText: "View documentation",
      href: "https://docs.tez.capital/tezpay/",
    },
    {
      icon: Activity,
      title: "TezCool",
      description: "Comprehensive analytics, visualization, and ecosystem data for Tezos.",
      linkText: "Visit website",
      href: "https://tez.cool/",
    },
    {
      icon: Database,
      title: "Tzinit Snapshots",
      description: "Fast and reliable snapshot service for bootstrapping your Tezos node quickly.",
      linkText: "Get snapshots",
      href: "https://snapshots.tzinit.org/",
    },
    {
      icon: LineChart,
      title: "TzKT Explorer",
      description: "Advanced Tezos block explorer with detailed baking statistics and API.",
      linkText: "View explorer",
      href: "https://tzkt.io",
    },
    {
      icon: Search,
      title: "TzStats",
      description: "Block explorer for Tezos with comprehensive network analytics and statistics.",
      linkText: "Visit explorer",
      href: "https://tzstats.com/",
    },
    {
      icon: Bell,
      title: "Tezos Notifier Bot",
      description: "Telegram bot that notifies bakers about transactions and other blockchain events.",
      linkText: "Open bot",
      href: "https://t.me/TezosNotifierBot",
    },
    {
      icon: Coins,
      title: "Stake Tezos",
      description: "User-friendly interface to stake tez and delegate to bakers on the Tezos network.",
      linkText: "Stake now",
      href: "https://stake.tezos.com/",
    },
    {
      icon: BarChart,
      title: "Bake Around Find Out",
      description: "Comprehensive performance analysis and insights for Tezos bakers.",
      linkText: "Visit website",
      href: "https://bafo.fafolab.xyz/",
    },
    {
      icon: Code,
      title: "Octez Suite",
      description: "Command-line client for interacting with Tezos and running nodes.",
      linkText: "View documentation",
      href: "https://docs.tezos.com/developing/octez-client",
    },
    {
      icon: Plus,
      title: "More to come",
      description: "Additional tools and resources will be added regularly.",
      linkText: "",
      href: "#",
    },
  ],
  images: {
    background: "/images/gradient-bg-bottom-left.webp",
  },
}
